export const itemCategories = [
	"Facemasks",
	"Disinfectant spray gun",
	"Clothes",
	"Socks",
	"Pants",
	"Bra",
	"Panty",
	"Shoes",
	"Shoe accessories",
	"Bags",
	"Luggage",
	"Cap",
	"Belt",
	"Scarf",
	"Glove",
	"Glasses",
	"Contact Lens",
	"Watch",
	"Jewelleries",
	"Skincare",
	"Cosmetics",
	"Hair care",
	"Fragrance",
	"Phone accessories",
	"Mobile phone",
	"Computer parts",
	"Car Parts",
	"Car care",
	"Organizers",
	"Daily items",
	"Stationaries",
	"Office supplies",
	"Electronics (Household)",
	"Decoration",
	"Bed sheet",
	"Household items",
	"Toiletries",
	"Camera accessories",
	"Toys or models",
	"Baby items",
	"Baby chair",
	"Furniture",
	"Cleaning items",
	"Music instruments",
	"Fitness gear",
	"Renovation material",
	"Electronic parts",
	"Garden supplies",
	"Machine parts",
	"Camping stuff",
	"Snack",
	"Dried Food",
	"Tea",
	"Coffee",
	"Supplements",
	"Can Drinks",
	"Bicycle",
	"Pet supply",
	"Fishing supply",
	"Hair trimming supply",
	"Games",
	"Kitchenware",
	"Books",
	"Sports Equipment",
	"Medical Use",
].sort();
export const currencies = ["MYR", "BND", "SGD", "USD", "CNY", "JPY"];
export const couriers = [
	"ABX Express",
	"Airpak Express",
	"ARAMEX",
	"Asiaxpress",
	"City-Link Express",
	"DeliveryLah",
	"DHL Express",
	"DPEX",
	"FEDEX",
	"GD Express",
	"UPS",
	"Ninja Van",
	"Pos Laju",
	"Singpost",
	"J&T",
	"Others",
];
export const deliveryMethods = ["Self-Pickup", "Select Soon"];

export const MOHPharmacies = ["Skincare", "Cosmetics", "Hair care", "Fragrance", "Essential oils", "Medical Use"];
export const MOHFoodSafeties = ["Snack", "Dried Food", "Tea", "Coffee", "Supplements", "Can Drinks"];
export const AITI = ["Electronics (Household)", "Camera accessories", "Computer parts", "Watch", "Phone accessories", "Mobile phone"];
export const internalSecurities = ["Books"];
